# Generated by Django 4.2.11 on 2026-08-13 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0003_recommendation_explanation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillGapSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matched_skills', models.JSONField(blank=True, default=list)),
                ('missing_skills', models.JSONField(blank=True, default=list)),
                ('priority_skills', models.JSONField(blank=True, default=list, help_text='Missing skills ranked by importance')),
                ('learning_suggestions', models.JSONField(blank=True, default=list)),
                ('match_percentage', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_gap_snapshots', to='jobs.job')),
                ('job_seeker', models.ForeignKey(limit_choices_to={'role': 'job_seeker'}, on_delete=django.db.models.deletion.CASCADE, related_name='skill_gap_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'swipex_skill_gap_snapshots',
                'ordering': ['-created_at'],
            },
        ),
    ]
