# Generated by hand for SwipeX

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('role', models.CharField(choices=[('job_seeker', 'Job Seeker'), ('recruiter', 'Recruiter'), ('admin', 'Admin')], default='job_seeker', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('company_logo', models.URLField(blank=True, max_length=512, null=True)),
                ('description', models.TextField()),
                ('salary_range', models.CharField(blank=True, max_length=100, null=True)),
                ('salary_min', models.IntegerField(default=0)),
                ('salary_max', models.IntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('required_skills', models.JSONField(blank=True, default=list)),
                ('organization_type', models.CharField(choices=[('mnc', 'MNC'), ('startup', 'Startup'), ('newly_founded', 'Newly Founded Startup')], default='startup', max_length=20)),
                ('job_type', models.CharField(choices=[('remote', 'Remote'), ('internship', 'Internship'), ('full_time', 'Full Time')], default='full_time', max_length=20)),
                ('experience_level', models.CharField(choices=[('fresher', 'Fresher'), ('junior', 'Junior'), ('mid', 'Mid-Level'), ('senior', 'Senior')], default='junior', max_length=20)),
                ('is_fresher_friendly', models.BooleanField(default=False)),
                ('applicant_count', models.IntegerField(default=0)),
                ('competition_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_posted', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=150, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('avatar_url', models.URLField(blank=True, max_length=512, null=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('resume_url', models.URLField(blank=True, max_length=512, null=True)),
                ('company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('company_website', models.URLField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('swiped_left', 'Swiped Left'), ('swiped_right', 'Swiped Right'), ('matched', 'Matched'), ('interviewing', 'Interviewing'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='swiped_right', max_length=20)),
                ('seeker_feedback', models.TextField(blank=True, null=True)),
                ('recruiter_feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='api.job')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes', to='api.user')),
            ],
            options={
                'verbose_name_plural': 'Matches',
                'unique_together': {('seeker', 'job')},
            },
        ),
    ]
