# Generated by Django 4.2.11 on 2026-07-29 06:44

import apps.resumes.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.resumes.models.resume_upload_path)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX')], max_length=10)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='Size in bytes')),
                ('is_primary', models.BooleanField(default=True, help_text='Active resume used for ATS scoring & recommendations')),
                ('raw_text', models.TextField(blank=True)),
                ('parsed_name', models.CharField(blank=True, max_length=255)),
                ('parsed_email', models.CharField(blank=True, max_length=255)),
                ('parsed_phone', models.CharField(blank=True, max_length=50)),
                ('parsed_skills', models.JSONField(blank=True, default=list)),
                ('parsed_technologies', models.JSONField(blank=True, default=list)),
                ('parsed_education', models.JSONField(blank=True, default=list)),
                ('parsed_experience', models.JSONField(blank=True, default=list)),
                ('parsed_projects', models.JSONField(blank=True, default=list)),
                ('parsed_certifications', models.JSONField(blank=True, default=list)),
                ('has_github_link', models.BooleanField(default=False)),
                ('has_linkedin_link', models.BooleanField(default=False)),
                ('estimated_years_experience', models.FloatField(default=0)),
                ('parse_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('parse_error', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(limit_choices_to={'role': 'job_seeker'}, on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'swipex_resumes',
                'ordering': ['-is_primary', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ATSScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_score', models.FloatField(default=0.0, help_text='0-100')),
                ('skill_match', models.FloatField(default=0.0)),
                ('experience_match', models.FloatField(default=0.0)),
                ('keyword_match', models.FloatField(default=0.0)),
                ('education_match', models.FloatField(default=0.0)),
                ('matched_skills', models.JSONField(blank=True, default=list)),
                ('missing_skills', models.JSONField(blank=True, default=list)),
                ('missing_keywords', models.JSONField(blank=True, default=list)),
                ('suggestions', models.JSONField(blank=True, default=list)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ats_scores', to='jobs.job')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ats_scores', to='resumes.resume')),
            ],
            options={
                'db_table': 'swipex_ats_scores',
                'ordering': ['-overall_score'],
                'unique_together': {('resume', 'job')},
            },
        ),
    ]
