# Generated by Django 4.2.11 on 2026-07-31 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='parsed_github_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='resume',
            name='parsed_linkedin_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
