# Generated by Django 4.2.11 on 2026-08-13 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0003_recommendation_explanation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('new_job', 'New Job Match'), ('high_match', 'High Match Job Alert'), ('low_competition', 'Low Competition Job Alert'), ('resume_reminder', 'Resume Improvement Reminder'), ('saved_job_reminder', 'Saved Job Reminder'), ('application_status', 'Application Status Update'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('new_application', 'New Application'), ('candidate_shortlist_suggestion', 'Candidate Shortlist Suggestion'), ('job_expiration_reminder', 'Job Expiration Reminder'), ('system', 'System')], default='system', max_length=40)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=10)),
                ('link', models.CharField(blank=True, help_text='Frontend route, e.g. /jobs/<id>', max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='jobs.jobapplication')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'swipex_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='swipex_noti_user_id_252523_idx'), models.Index(fields=['user', '-created_at'], name='swipex_noti_user_id_871be2_idx')],
            },
        ),
    ]
