# Generated by Django 4.2.11 on 2026-08-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_job', 'New Job Match'), ('startup_hiring', 'Startup Hiring Alert'), ('high_match', 'High Match Job Alert'), ('low_competition', 'Low Competition Job Alert'), ('resume_reminder', 'Resume Improvement Reminder'), ('saved_job_reminder', 'Saved Job Reminder'), ('application_status', 'Application Status Update'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('new_application', 'New Application'), ('candidate_shortlist_suggestion', 'Candidate Shortlist Suggestion'), ('job_expiration_reminder', 'Job Expiration Reminder'), ('system', 'System')], default='system', max_length=40),
        ),
    ]
