import React, { useState, useEffect } from 'react';
import { 
  Sparkles, Download, Share2, FileText, CheckCircle2, 
  AlertTriangle, TrendingUp, Award, UploadCloud, X, Check, Loader2 
} from 'lucide-react';
import api from '../utils/api';
import { useToast } from '../context/ToastContext';

export default function AtsAnalyzer({ onAnalysisUpdate }) {
  const { showToast } = useToast();
  
  // Stored analysis data states
  const [analysis, setAnalysis] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  
  // Upload and re-run states
  const [dragActive, setDragActive] = useState(false);
  const [uploadFile, setUploadFile] = useState(null);
  const [processing, setProcessing] = useState(false);

  const fetchLatestAnalysis = async () => {
    setLoading(true);
    setError(null);
    try {
      const response = await api.get('/profiles/ai/analyze-resume/');
      setAnalysis(response.data);
      if (onAnalysisUpdate) {
        onAnalysisUpdate(response.data);
      }
    } catch (err) {
      console.error("Failed to load ATS analysis:", err);
      setError(err.response?.data?.detail || "Could not retrieve ATS analysis.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchLatestAnalysis();
  }, []);

  const handleDrag = (e) => {
    e.preventDefault();
    e.stopPropagation();
    if (e.type === "dragenter" || e.type === "dragover") {
      setDragActive(true);
    } else if (e.type === "dragleave") {
      setDragActive(false);
    }
  };

  const handleDrop = (e) => {
    e.preventDefault();
    e.stopPropagation();
    setDragActive(false);
    
    if (e.dataTransfer.files && e.dataTransfer.files[0]) {
      validateAndSetFile(e.dataTransfer.files[0]);
    }
  };

  const handleFileChange = (e) => {
    if (e.target.files && e.target.files[0]) {
      validateAndSetFile(e.target.files[0]);
    }
  };

  const validateAndSetFile = (file) => {
    const ext = file.name.split('.').pop().toLowerCase();
    if (!['pdf', 'doc', 'docx'].includes(ext)) {
      showToast("Only PDF, DOC, and DOCX resume formats are supported.", "error");
      return;
    }
    if (file.size > 5 * 1024 * 1024) {
      showToast("Resume file size cannot exceed 5MB.", "error");
      return;
    }
    setUploadFile(file);
    showToast(`Loaded ${file.name} successfully. Confirm upload to re-run ATS analysis.`, "info");
  };

  const handleResumeUpload = async () => {
    if (!uploadFile) return;
    setProcessing(true);
    const formData = new FormData();
    formData.append('file', uploadFile);

    try {
      // 1. Upload resume file
      const uploadRes = await api.post('/profiles/me/resume/', formData, {
        headers: { 'Content-Type': 'multipart/form-data' }
      });
      showToast('Resume file stored. Initializing parser analysis...', 'info');

      // 2. Re-run analysis
      const analysisRes = await api.post('/profiles/ai/analyze-resume/', {
        resume_id: uploadRes.data.id
      });
      
      setAnalysis(analysisRes.data);
      if (onAnalysisUpdate) {
        onAnalysisUpdate(analysisRes.data);
      }
      setUploadFile(null);
      showToast('ATS Score refreshed successfully!', 'success');
    } catch (err) {
      console.error(err);
      showToast(err.response?.data?.error || 'Failed to complete resume analysis.', 'error');
    } finally {
      setProcessing(false);
    }
  };

  const handleDownloadReport = () => {
    if (!analysis) return;
    const score = analysis.overall_score || analysis.score || 0;
    const grade = analysis.score_grade || "Unknown";
    const strengths = (analysis.strengths || []).join("\n- ");
    const gaps = (analysis.missing_keywords || []).join(", ");
    const improvements = (analysis.improvements || []).join("\n- ");

    const content = `=========================================
SWIPEX ATS ANALYZER ASSESSMENT REPORT
=========================================
Overall ATS Score: ${score}%
Resume Grade: ${grade}
Primary Target: Senior Developer Track

STRENGTHS DETECTED:
- ${strengths || 'Profile foundations parsed successfully.'}

CRITICAL SKILL GAPS:
${gaps ? `Missing Keywords: ${gaps}` : 'No critical skill gaps found! Great coverage.'}

RECOMMENDATIONS FOR IMPROVEMENT:
- ${improvements || 'Maintain updated portfolio urls.'}

=========================================
Generated by SwipeX AI Studio.
    `;
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `SwipeX_ATS_Report_${analysis.overall_score || '88'}.txt`;
    link.click();
    showToast('ATS Report downloaded successfully!', 'success');
  };

  const handleShareResult = () => {
    if (!analysis) return;
    const score = analysis.overall_score || analysis.score || 0;
    navigator.clipboard.writeText(`I just scanned my resume on SwipeX AI Job platform and achieved an ATS compatibility score of ${score}%! Join at swipex.co`);
    showToast('Copied shareable ATS scorecard to clipboard!', 'success');
  };

  if (loading) {
    return (
      <div className="min-h-[60vh] flex flex-col items-center justify-center space-y-4">
        <Loader2 className="w-12 h-12 text-blue-600 animate-spin" />
        <span className="text-slate-500 text-xs font-black uppercase tracking-widest animate-pulse">Running ATS Audits...</span>
      </div>
    );
  }

  if (error) {
    return (
      <div className="p-6 rounded-[24px] bg-rose-50 border border-rose-100 text-center space-y-4">
        <AlertTriangle className="w-12 h-12 text-rose-500 mx-auto" />
        <h3 className="text-lg font-black text-slate-800">ATS Analysis Failed</h3>
        <p className="text-xs text-slate-500 max-w-md mx-auto">{error}</p>
        <button 
          onClick={fetchLatestAnalysis}
          className="px-6 py-2.5 rounded-full bg-gradient-to-r from-blue-600 to-indigo-600 text-white font-extrabold text-xs uppercase tracking-wider hover:scale-102 transition-all cursor-pointer shadow-md shadow-blue-500/10"
        >
          Try Again
        </button>
      </div>
    );
  }

  // Extracted fields
  const atsScore = analysis.overall_score || analysis.score || 0;
  const scoreGrade = analysis.score_grade || "Fair";
  const matchedKeywords = analysis.matched_keywords || [];
  const missingKeywords = analysis.missing_keywords || [];
  const improvements = analysis.improvements || [];

  return (
    <div className="space-y-6 text-left text-slate-800">
      {/* 1. TOP HEADER */}
      <div className="flex flex-col md:flex-row md:items-center md:justify-between p-6 rounded-[24px] bg-white border border-slate-200/80 gap-6 shadow-md">
        <div className="space-y-2">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full border border-blue-200 bg-blue-50 text-[9px] font-black uppercase tracking-widest text-blue-600">
            <CheckCircle2 size={12} className="text-blue-600" />
            <span>ANALYSIS COMPLETE</span>
          </div>
          <div className="flex items-center gap-2">
            <h1 className="text-xl md:text-2xl font-black text-slate-800 tracking-tight">ATS Analysis Complete</h1>
            <span className="text-[10px] text-slate-650 font-extrabold uppercase bg-slate-50 px-2 py-0.5 rounded border border-slate-205">
              ID: ATS-{(atsScore * 13 + 472).toString(16).toUpperCase()}
            </span>
          </div>
          <p className="text-xs text-slate-500 font-semibold max-w-xl">
            {analysis?.is_job_match 
              ? `We scanned your resume against the selected job post: "${analysis?.job_title}". Below is your compatibility scorecard.`
              : "We scanned your latest uploaded resume against industry benchmarks. Below is your structured parsing scorecard."}
          </p>
        </div>
        <div className="flex items-center gap-2.5 shrink-0">
          <button 
            onClick={handleDownloadReport}
            className="flex items-center gap-2 px-4 py-2.5 bg-white border border-slate-200 hover:bg-slate-50 text-slate-650 hover:text-blue-600 rounded-xl text-[10px] font-black uppercase tracking-wider transition-all cursor-pointer shadow-sm"
          >
            <Download size={12} />
            <span>Download Report</span>
          </button>
          <button 
            onClick={handleShareResult}
            className="flex items-center gap-2 px-4 py-2.5 bg-gradient-to-r from-blue-600 to-indigo-600 text-white rounded-xl text-[10px] font-black uppercase tracking-wider hover:scale-102 transition-all cursor-pointer shadow-md shadow-blue-500/10"
          >
            <Share2 size={12} />
            <span>Share Result</span>
          </button>
        </div>
      </div>

      {/* 2. MAIN DASHBOARD */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        
        {/* A. ATS Score card */}
        <div className="lg:col-span-4 p-6 rounded-[24px] bg-white border border-slate-205 flex flex-col justify-between shadow-md relative overflow-hidden">
          <div className="absolute top-0 right-0 -translate-y-1/3 translate-x-1/3 w-32 h-32 bg-blue-600/5 rounded-full blur-2xl pointer-events-none" />
          <div className="space-y-4 text-center">
            <span className="text-[10px] font-black uppercase tracking-widest text-slate-400 block border-b border-slate-100 pb-2">
              {analysis?.is_job_match ? 'Job Match ATS Score' : 'General ATS Score'}
            </span>
            
            {/* Score Ring */}
            <div className="relative w-36 h-36 mx-auto flex items-center justify-center shrink-0">
              <svg className="w-full h-full transform -rotate-90" viewBox="0 0 36 36">
                <circle cx="18" cy="18" r="16" fill="none" stroke="#f1f5f9" strokeWidth="2.5" />
                <circle cx="18" cy="18" r="16" fill="none" stroke="url(#ats-dash-grad)" strokeWidth="3"
                  strokeDasharray={`${atsScore}, 100`} strokeLinecap="round" className="transition-all duration-1000 ease-out" />
                <defs>
                  <linearGradient id="ats-dash-grad" x1="0%" y1="0%" x2="100%" y2="100%">
                    <stop offset="0%" stopColor="#2563eb" />
                    <stop offset="100%" stopColor="#4f46e5" />
                  </linearGradient>
                </defs>
              </svg>
              <div className="absolute flex flex-col items-center">
                <span className="text-4xl font-black text-slate-800">{atsScore}%</span>
                <span className="text-[8px] font-bold text-slate-500 uppercase tracking-widest">{scoreGrade}</span>
              </div>
            </div>

            <div className="py-2.5">
              <span className="text-xs font-black text-blue-600">Resume Strength: {analysis.recruiter_view?.resume_strength || "Fair"}</span>
            </div>
          </div>

          <div className="border-t border-slate-100 pt-4 mt-4 space-y-3 text-[10px] font-bold text-slate-500">
            <div className="flex justify-between">
              <span className="text-slate-400">Best Match</span>
              <span className="text-slate-700">{analysis.best_match || "Senior Developer"}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-slate-400">Confidence</span>
              <span className="text-emerald-600">{analysis.confidence_score || 90}%</span>
            </div>
            <div className="flex justify-between">
              <span className="text-slate-400">Compatibility</span>
              <span className="text-blue-600">{analysis.compatibility || "Needs Review"}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-slate-400">Career Path</span>
              <span className="text-indigo-600">{analysis.career_path || "Staff Dev Track"}</span>
            </div>
          </div>
        </div>

        {/* B. Skill Radar (Custom visual bars) */}
        <div className="lg:col-span-8 p-6 rounded-[24px] bg-white border border-slate-205 shadow-md flex flex-col justify-between">
          <div className="space-y-4">
            <span className="text-[10px] font-black uppercase tracking-widest text-blue-600 block border-b border-slate-100 pb-2">Technical Skill Visualization</span>
            <p className="text-[10px] text-slate-550 leading-relaxed font-semibold">
              Parser engine evaluation of primary technical skill nodes detected across project listings.
            </p>
            
            <div className="space-y-3.5 pt-2">
              {[
                { label: "Technology (Core Stack)", val: analysis.keyword_score ?? 0, color: "from-blue-650 to-indigo-650" },
                { label: "Tools & Architectures", val: analysis.certification_score ?? 0, color: "from-blue-500 to-indigo-500" },
                { label: "Experience Match Score", val: analysis.experience_score ?? 0, color: "from-blue-600 to-indigo-600" },
                { label: "Soft Skills & Teamwork", val: analysis.skills_score ?? 0, color: "from-blue-400 to-indigo-400" }
              ].map((bar, idx) => (
                <div key={idx} className="space-y-1.5">
                  <div className="flex justify-between text-xxs font-black uppercase text-slate-500">
                    <span>{bar.label}</span>
                    <span>{bar.val}%</span>
                  </div>
                  <div className="w-full h-2 rounded-full bg-slate-100 overflow-hidden relative border border-slate-200">
                    <div 
                      className={`h-full bg-gradient-to-r ${bar.color} transition-all duration-1000`} 
                      style={{ width: `${bar.val}%` }}
                    />
                  </div>
                </div>
              ))}
            </div>
          </div>
          
          <div className="pt-4 border-t border-slate-100 mt-4 flex items-center gap-2 text-[9px] text-slate-500 font-extrabold uppercase tracking-wider">
            <Award size={12} className="text-blue-600 animate-bounce" />
            <span>Highest compatibility domain: {analysis.highest_compatibility_domain || "General Professional Services"}</span>
          </div>
        </div>

      </div>

      {/* 3. HEATMAP & GAPS */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        
        {/* C. Heatmap Analysis */}
        <div className="p-6 rounded-[24px] bg-white border border-slate-205 shadow-md space-y-4">
          <span className="text-[10px] font-black uppercase tracking-widest text-slate-400 block border-b border-slate-100 pb-2">Heatmap Analysis</span>
          
          <div className="grid grid-cols-3 gap-3">
            {[
              { label: "Keywords Found", val: `${matchedKeywords.length} tags`, desc: "High density matched" },
              { label: "Formatting Health", val: `${analysis.formatting_score ?? 0}%`, desc: "Standard margins" },
              { label: "Parse Stability", val: `${analysis.grammar_score ?? 0}%`, desc: "JSON structured" }
            ].map((item, idx) => (
              <div key={idx} className="p-3 rounded-xl bg-slate-50 border border-slate-200/80 text-center">
                <span className="text-[8px] font-black text-slate-450 uppercase block">{item.label}</span>
                <p className="text-sm font-black text-slate-800 mt-1.5">{item.val}</p>
                <span className="text-[7px] text-slate-500 font-semibold block mt-1">{item.desc}</span>
              </div>
            ))}
          </div>

          <div className="space-y-2 pt-2">
            <span className="text-[9px] font-black text-slate-450 uppercase tracking-widest block">Detected Skills</span>
            <div className="flex flex-wrap gap-1.5">
              {matchedKeywords.length > 0 ? (
                matchedKeywords.map((kw) => (
                  <span key={kw} className="px-2.5 py-1 rounded-lg bg-emerald-50 border border-emerald-200 text-emerald-700 text-[10px] font-black uppercase tracking-wider">
                    {kw}
                  </span>
                ))
              ) : (
                <span className="text-xxs text-slate-500 italic">No keywords detected yet. Upload a resume to scan.</span>
              )}
            </div>
          </div>
        </div>

        {/* D. Critical Skill Gaps */}
        <div className="p-6 rounded-[24px] bg-white border border-slate-205 shadow-md space-y-4 flex flex-col justify-between">
          <div className="space-y-4">
            <span className="text-[10px] font-black uppercase tracking-widest text-blue-600 block border-b border-slate-100 pb-2">Critical Skill Gaps</span>
            
            <div className="flex flex-wrap gap-2">
              {missingKeywords.length > 0 ? (
                missingKeywords.map((kw) => (
                  <span key={kw} className="px-2.5 py-1 rounded-lg bg-rose-50 border border-rose-100 text-rose-600 text-[10px] font-black uppercase tracking-wider">
                    + {kw}
                  </span>
                ))
              ) : (
                <div className="p-4 rounded-xl bg-emerald-50 border border-emerald-100 w-full flex items-center gap-3">
                  <CheckCircle2 className="w-5 h-5 text-emerald-600 shrink-0" />
                  <p className="text-xxs font-bold text-emerald-800 leading-relaxed">
                    No critical skill gaps found! Your resume has parsed coverage on all targeted backend/frontend skills.
                  </p>
                </div>
              )}
            </div>
          </div>

          <div className="p-3.5 rounded-xl bg-slate-50 border border-slate-200 space-y-2 mt-4">
            <span className="text-[9px] font-black text-slate-450 uppercase tracking-widest block">Actionable Recommendations</span>
            <div className="space-y-1.5">
              {improvements.length > 0 ? (
                improvements.map((imp, idx) => (
                  <div key={idx} className="flex gap-2 text-xxs text-slate-600 font-semibold leading-relaxed">
                    <span className="text-blue-600 font-black">•</span>
                    <span>{imp}</span>
                  </div>
                ))
              ) : (
                <p className="text-xxs text-slate-500 italic">No suggestions required. Resume matches targeted senior engineer stack.</p>
              )}
            </div>
          </div>
        </div>

      </div>

      {/* 4. FAST ITERATION (Upload Resume dropzone) */}
      <div className="p-6 rounded-[24px] bg-white border border-slate-205 shadow-md space-y-4">
        <span className="text-[10px] font-black uppercase tracking-widest text-slate-400 block border-b border-slate-100 pb-2">Revised Resume Upload</span>
        
        <div className="grid md:grid-cols-2 gap-6 items-center">
          <div 
            onDragEnter={handleDrag}
            onDragOver={handleDrag}
            onDragLeave={handleDrag}
            onDrop={handleDrop}
            className={`p-6 rounded-[20px] border-2 border-dashed text-center space-y-3 transition-all relative ${
              dragActive 
                ? 'border-blue-500 bg-blue-50/50' 
                : 'border-slate-200 bg-slate-50/50 hover:border-slate-300'
            }`}
          >
            <input 
              type="file" 
              id="file-upload-input"
              className="hidden" 
              onChange={handleFileChange}
              accept=".pdf,.doc,.docx"
              disabled={processing}
            />
            <label 
              htmlFor="file-upload-input" 
              className="cursor-pointer flex flex-col items-center space-y-2"
            >
              <UploadCloud className="w-10 h-10 text-blue-600 animate-pulse" />
              <span className="text-xs font-black text-slate-800 uppercase tracking-wider">Drag & Drop Resume File</span>
              <span className="text-[10px] text-slate-450 font-extrabold uppercase">PDF, DOCX, DOC files up to 5MB</span>
            </label>
          </div>

          <div className="space-y-4">
            <h4 className="text-xs font-black text-slate-850">Optimize & Re-Run</h4>
            <p className="text-[10px] text-slate-500 leading-relaxed font-semibold">
              Corrected the missing keywords on your local CV copy? Drop it here and trigger a re-run to refresh your SwipeX matching analytics.
            </p>

            {uploadFile && (
              <div className="p-3 rounded-xl bg-slate-105 border border-slate-200 flex items-center justify-between shadow-sm">
                <div className="flex items-center space-x-2.5 min-w-0">
                  <FileText className="w-4 h-4 text-blue-600 shrink-0" />
                  <span className="text-[10px] font-bold text-slate-800 truncate">{uploadFile.name}</span>
                </div>
                <button 
                  onClick={() => setUploadFile(null)}
                  className="p-1 rounded-full text-slate-500 hover:text-red-500 hover:bg-slate-200"
                >
                  <X size={12} />
                </button>
              </div>
            )}

            <button 
              onClick={handleResumeUpload}
              disabled={!uploadFile || processing}
              className="w-full flex items-center justify-center space-x-2 py-3 bg-gradient-to-r from-blue-600 to-indigo-650 text-white font-extrabold text-xs uppercase tracking-wider rounded-xl hover:scale-102 hover:shadow-lg hover:shadow-blue-500/10 transition-all cursor-pointer shadow-md disabled:opacity-40 disabled:scale-100 disabled:cursor-not-allowed disabled:shadow-none"
            >
              {processing ? (
                <>
                  <Loader2 size={14} className="animate-spin text-white" />
                  <span>Processing Analysis...</span>
                </>
              ) : (
                <>
                  <Sparkles size={14} />
                  <span>Analyze Revised Resume</span>
                </>
              )}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
