from django.urls import path
from .views import (
    JobCreateView,
    JobDetailView,
    RecruiterJobsListView,
    JobApplicantsListView,
    ApplicationStatusUpdateView,
    RecruiterAnalyticsView,
    JobDeckView,
    SwipeActionView,
    SwipeUndoView,
    JobSearchView,
    SeekerApplicationsListView,
    InterviewListCreateView,
    InterviewResponseView,
    MyInterviewsListView,
    CompanyDetailView,
    SeekerDashboardView,
    ResetSwipesView,
    AICoverLetterGeneratorView,
    AIInterviewQuestionsView,
    AISkillGapAnalysisView,
    BulkJobUploadView
)

urlpatterns = [
    path('bulk-upload/', BulkJobUploadView.as_view(), name='bulk_job_upload'),
    path('', JobCreateView.as_view(), name='job_create'),
    path('recruiter-jobs/', RecruiterJobsListView.as_view(), name='recruiter_jobs_list'),
    path('recruiter-analytics/', RecruiterAnalyticsView.as_view(), name='recruiter_analytics'),
    path('companies/<uuid:pk>/', CompanyDetailView.as_view(), name='company_detail'),
    path('deck/', JobDeckView.as_view(), name='job_deck'),
    path('recommendations/', JobDeckView.as_view(), name='job_recommendations'),
    path('swipe/', SwipeActionView.as_view(), name='job_swipe'),
    path('swipe/undo/', SwipeUndoView.as_view(), name='job_swipe_undo'),
    path('swipe/reset/', ResetSwipesView.as_view(), name='job_swipe_reset'),
    path('seeker-dashboard/', SeekerDashboardView.as_view(), name='seeker_dashboard'),
    path('search/', JobSearchView.as_view(), name='job_search'),
    path('my-applications/', SeekerApplicationsListView.as_view(), name='my_applications'),
    path('interviews/', InterviewListCreateView.as_view(), name='interview_list_create'),
    path('interviews/<uuid:pk>/respond/', InterviewResponseView.as_view(), name='interview_respond'),
    path('my-interviews/', MyInterviewsListView.as_view(), name='my_interviews'),
    path('ai/generate-cover-letter/', AICoverLetterGeneratorView.as_view(), name='ai_cover_letter'),
    path('ai/generate-interview-questions/', AIInterviewQuestionsView.as_view(), name='ai_interview_questions'),
    path('ai/skill-gap-analysis/', AISkillGapAnalysisView.as_view(), name='ai_skill_gap'),
    path('<uuid:pk>/', JobDetailView.as_view(), name='job_detail'),
    path('<uuid:job_id>/applicants/', JobApplicantsListView.as_view(), name='job_applicants'),
    path('applications/<uuid:pk>/status/', ApplicationStatusUpdateView.as_view(), name='application_status_update'),
]
