# Generated by Django 4.2.11 on 2026-07-31 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='recruiter_notes',
            field=models.TextField(blank=True, help_text='Private notes visible only to the recruiter'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='status_history',
            field=models.JSONField(blank=True, default=list, help_text='[{status, changed_at (iso), note}] — audit trail of every status change'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Applied'), ('reviewed', 'Resume Reviewed'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('interview_completed', 'Interview Completed'), ('offered', 'Offered'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20),
        ),
    ]
