# Generated by Django 4.2.11 on 2026-08-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobapplication_recruiter_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='explanation',
            field=models.JSONField(blank=True, default=dict, help_text='Milestone 4: structured breakdown — matched/missing skills, ATS score, factor weights'),
        ),
    ]
