# Generated by Django 6.0.7 on 2026-07-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_swipehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.CharField(choices=[('startup', 'Startup'), ('mnc', 'MNC')], default='mnc', max_length=20),
        ),
    ]
