# Generated by Django 4.2.30 on 2026-07-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_application_status_alter_interview_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='original_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='job',
            name='provider',
            field=models.CharField(db_index=True, default='native', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='provider_job_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
