# Generated by Django 4.2.30 on 2026-07-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_job_expires_at_job_original_url_job_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='rating',
            field=models.FloatField(default=4.0),
        ),
        migrations.AddField(
            model_name='job',
            name='ai_match_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='apply_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='job',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='country',
            field=models.CharField(db_index=True, default='United States', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='state',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
