# Generated by Django 4.2.30 on 2026-08-08 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_profile_picture_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='ats_analysis',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
